#!/bin/bash

function bash.utils.quit() {
  local ln="${1?}"
  printf "%s" "[EXIT]: ${ln}"
  exit 1
}

functions bash.utils.is_root() {
  [[ "${UID}" -eq 0 ]] \
  || bash.utils.quit 'You must be root to execute this script'
}

function bash.utils.consoleLog()
{
  local ln="${1?}"
  printf "%s %s" "$(date +'%a %Y-%m-%d %H:%M:%S %z')" "${ln}"
}

function bash.utils.writeln() {
  local ln="${1?}"
  printf "%s" "${ln}"
}

function bash.utils.is_empty() {
  # Check value is not empty and a number
  if [[ -z "${1}" ]]; then
      # return 0, is empty
      return 0
  fi
  # return 1, not empty
  return 1
}

function bash.utils.find_os_family() {
  # Detect Linux or Darwin
  printf "%s" "$(uname -s)"
}
